// FOR THE LOVE OF GOD, PLEASE REMEMBER TO INCLUDE THIS ANYWHERE THAT USES GLM. CAUSED HOURS OF TROUBLESHOOTING OBJLOADER.

#pragma once
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLM_FORCE_DEFAULT_ALIGNED_GENTYPES 
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
